import React, { useState, useEffect , useContext } from 'react'
import { AuthContext } from '../store/AuthContext'
import Head from 'next/head'
import Dashboard from './dashboard'
import useForm from './api/useLogin'
import Login from './login'

export default function Home() {
  const {
    values,
    isLogin,
    handleOnChange,
    handleSignIn,
    handleSignUp,
    handleLogOut,
    clearState,
  } = useForm()

  
  return (
    <div>
      <Head>
        <title>Social</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {isLogin ? (
          <Dashboard handleLogOut={handleLogOut} />
        ) : (
          <Login/>
        )}
      </main>
      <footer></footer>
    </div>
  )
}
