import React, { useState, useEffect } from 'react'
import Head from 'next/head'
import Dashboard from '../components/Dashboard/Dashboard'
import useForm from '../components/Form/useForm'
import Login from '../components/Form/Login'

export default function Home() {
  const {
    values,
    isLogin,
    handleOnChange,
    handleSignIn,
    handleSignUp,
    handleLogOut,
    clearState,
  } = useForm()

  return (
    <div>
      <Head>
        <title>Social</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {isLogin ? (
          <Dashboard handleLogOut={handleLogOut} />
        ) : (
          <Login
            values={values}
            handleOnChange={handleOnChange}
            handleSignIn={handleSignIn}
            handleSignUp={handleSignUp}
            clearState={clearState}
          />
        )}
      </main>

      <footer></footer>
    </div>
  )
}
